#!/bin/bash

cd /home/ubuntu

# Git + setup
type="32bit_ami"
gist=$1
yes | apt-get install git
git clone https://$username:$password@github.com/gist/$gist.git
chmod a+x $gist/*
source $gist/credentials # is extended by
  source $gist/common # is extended by
    source $gist/base # is extended by this

setup_instance >> setup_instance.log 2>&1

# Bundle AMI
ami="$github_account_name-$type"
build_ami $ami >> build_ami.log 2>&1

# Terminate
curl "http://$2/aws/ec2/terminate/$instanceId"