#!/bin/bash

cd /home/ubuntu

# Git + setup
type=admin
gist=$1
yes | apt-get install git
git clone https://$username:$password@github.com/gist/$gist.git
chmod a+x $gist/*
source $gist/credentials # is extended by
  source $gist/common # is extended by
    source $gist/base # is extended by this

setup_instance >> setup_instance.log 2>&1

# Install instance-specific packages and applications
install_admin
  add_upstart_job $type "node /home/ubuntu/aws-bootstrap/$type/application.js"
  monitor_new_service application.js